---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustom-app
  template:
    metadata:
      labels:
        app: kustom-app
    spec:
      containers:
        - name: kustom-app
          imagePullPolicy: Always
          image: lazrb/nginx
          ports:
            - containerPort: 80
